import {
  KEY_ENTER,
  TEXT_SHOW_MORE,
  TEXT_SHOW_LESS,
  PAGINATION_LIMIT,
} from "utils/constant/form";
import {
  ICON_LOGO,
  LOGO_ICON_ALT_TEXT,
  ICON_SEARCH,
  SEARCH_ICON_ALT_TEXT,
  ICON_DELETE,
  DELETE_ICON_ALT_TEXT,
  ICON_COMPLETE,
  COMPLETE_ICON_ALT_TEXT,
  ICON_EDIT,
  EDIT_ICON_ALT_TEXT,
} from "utils/constant/images";

export {
  ICON_LOGO,
  LOGO_ICON_ALT_TEXT,
  ICON_SEARCH,
  SEARCH_ICON_ALT_TEXT,
  KEY_ENTER,
  TEXT_SHOW_MORE,
  TEXT_SHOW_LESS,
  PAGINATION_LIMIT,
  ICON_DELETE,
  DELETE_ICON_ALT_TEXT,
  ICON_COMPLETE,
  COMPLETE_ICON_ALT_TEXT,
  ICON_EDIT,
  EDIT_ICON_ALT_TEXT,
};
