export const ADD_TASK = "ADD_TASK";
export const TOGGlE_CREATE_BUTTON_VISIBILITY =
  "TOGGlE_CREATE_BUTTON_VISIBILITY";
export const DELETE_TASK = "DELETE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const TOGGlE_EDIT_BUTTON_VISIBILITY = "TOGGlE_EDIT_BUTTON_VISIBILITY";
